### ISSUE TITLE
install_github('elsasserlab/labcode', subdir='elsasserlib', build_vignettes = TRUE) fails

### ISSUE THREAD

**Issue by simonelsasser** [elsasserlab/labcode#17]
Error: (converted from warning) Setting LC_CTYPE failed, using "C"
Execution halted
Error: Failed to install 'elsasserlib' from GitHub:
  (converted from warning) installation of package 'BSgenome.Hsapiens.UCSC.hg38' had non-zero exit status

**Comment by cnluzon** [comment]
There seems to be a problem with instaling Bioconductor packages automatically on install. I am looking into it. 

As a workaround, have you tried installing it separately? 

    if (!requireNamespace("BiocManager", quietly = TRUE))
        install.packages("BiocManager")
    BiocManager::install("BSgenome.Hsapiens.UCSC.hg38")

**Comment by simonelsasser** [comment]
In the end it was some weird problems that could be indeed solved with installing individual things, sometimes as binary, sometimes from source whatever ran without error...
