### ISSUE TITLE
bw_bed does not handle empty bw file list

### ISSUE THREAD

**Issue by cnluzon** [elsasserlab/labcode#42]
If an empty list is passed to bw_bed (for instance, as a result of `list.files()` function for a bad path (or perhaps an empty directory) you get a `character(0)` object. In turn, when `bw_bed` is called:

```
> bw_bed(list.files(bad_path), 'my_bed_file')

 Error in h(simpleError(msg, call)) : 
  error in evaluating the argument 'x' in selecting a method for function 'sortSeqlevels': subscript out of bounds
``` 

This needs to be handled better because this output is very obscure.

**Comment by shaorray** [comment]
That's an argument check problem, sometimes needs to add `stopifnot(length(path) > 0)` or `if (length(path) == 0) stop("Empty path!")`
