### ISSUE TITLE
Couldn't find the function "bw_heatmap" in my local r package

### ISSUE THREAD

**Issue by YuyingCh** [elsasserlab/labcode#96]
Hi, 
I had updated the elsasserlib but somehow I couldn't find the function "bw_heatmap" in my local r. Any suggestions?

**Comment by cnluzon** [comment]
That's odd. Did you update it just now? Which version do you have? You can check both with `?elsasserlib` and it should also show in `sessionInfo()`. Latest version is `1.2.1`.

**Comment by YuyingCh** [comment]
ah sorry now it works after restarted the r studio :\ thanks.
